#!/usr/bin/env python3
"""
Sovereign Blackboard Architecture - Client Report Export

The engagement ends with a CLIENT-FACING document, not just engineer-facing
advisories: a single self-contained HTML with executive summary, CVSS
vectors, confirmed advisories (redacted), Mermaid attack-path diagrams, and
coverage honesty. Zero external dependencies (Mermaid renders from CDN in the
browser; the HTML degrades to readable text without it).

  * `export` — reports/client_report.html from the current board + reports/
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import quote

_engine_dir = str(Path(__file__).resolve().parent)
if _engine_dir not in sys.path:
    sys.path.insert(0, _engine_dir)
from board_io import load_json, blackboard_dir  # noqa: E402

BLACKBOARD_DIR = blackboard_dir()
BOARD_FILE = BLACKBOARD_DIR / "board.json"
REPORTS_DIR = Path.cwd() / "reports"

# Severity -> base CVSS 3.1 vector template (operators refine per-finding)
CVSS_TEMPLATES = {
    "critical": ("CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H", 9.3),
    "high": ("CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N", 7.4),
    "medium": ("CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N", 5.0),
    "low": ("CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:L/I:N/A:N", 3.1),
    "info": ("CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N", 0.0),
}


def _mermaid_chains(findings, board=None):
    """Render the chain graph as a Mermaid flowchart. Demonstrated (evidence-
    backed chain_to) edges are solid; hypo_edges (planner-proposed, unproven)
    render as dashed links labeled 'hypothetical'. Node labels resolve for
    findings AND leads via chain_planner.label_for (no bare LEAD_xxx)."""
    board = board or {}
    try:
        from chain_planner import label_for as _label
    except Exception:
        _label = lambda nid, _b: nid  # noqa: E731
    edges = []
    by_id = {f.get("id"): f for f in findings}
    for f in findings:
        for nxt in f.get("chain_to", []):
            if nxt in by_id:
                edges.append(f"    {f['id']}[\"{f.get('title', '')[:40]}\"] --> "
                             f"\"{nxt}\"[\"{(by_id[nxt].get('title') or '?')[:40]}\"]")
    hypo_lines = []
    for e in board.get("hypo_edges", []):
        a, b = e.get("from"), e.get("to")
        if not a or not b:
            continue
        la, lb = _label(a, board), _label(b, board)
        hypo_lines.append(f"    {a.replace('-', '_')}[\"{la[:40]}\"] -. \"hypothetical\" .-> "
                          f"{b.replace('-', '_')}[\"{lb[:40]}\"]")
    if not edges and not hypo_lines:
        return ""
    out = "```mermaid\nflowchart LR\n"
    out += "\n".join(edges + hypo_lines) + "\n```\n"
    return out


def export():
    board = load_json(BOARD_FILE) or {}
    findings = board.get("findings", [])
    confirmed = [f for f in findings if f.get("status") == "confirmed"]
    informational = [f for f in findings if f.get("status") != "confirmed"]
    leads = board.get("leads", [])
    untested = [l for l in leads if l.get("status") not in ("confirmed", "dead")]
    target = board.get("target_path") or "Target System"

    sev_counts = {}
    for f in confirmed:
        sev_counts[f.get("severity", "info")] = sev_counts.get(f.get("severity", "info"), 0) + 1

    sections = []
    sections.append(f"""
<div class="meta">Generated by the Artifactory Security Engine —
{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}</div>
<h1>Security Assessment Report</h1>
<h2>{target}</h2>
<div class="summary">
<b>{len(confirmed)}</b> confirmed vulnerabilities
(<span class="crit">{sev_counts.get('critical', 0)} critical</span>,
<span class="high">{sev_counts.get('high', 0)} high</span>,
<span class="med">{sev_counts.get('medium', 0)} medium</span>,
<span class="low">{sev_counts.get('low', 0)} low</span>)
&middot; {len(informational)} informational observations
&middot; {len(untested)} open items listed under coverage honesty.
</div>""")

    chains_md = _mermaid_chains(findings, board)
    if chains_md:
        sections.append("<h2>Attack Paths (demonstrated chains)</h2>" + chains_md)

    sections.append("<h2>Confirmed Vulnerabilities</h2>")
    for f in confirmed:
        sev = f.get("severity", "info")
        vec, score = CVSS_TEMPLATES.get(sev, CVSS_TEMPLATES["info"])
        evidence = (f.get("evidence") or "See evidence log.")[:600]
        sections.append(f"""
<div class="finding sev-{sev}">
<h3>[{sev.upper()}] {f.get('title', 'Untitled')}</h3>
<p>{f.get('details', '')}</p>
<p><b>CVSS:</b> <code>{vec}</code> (score {score}) — refine per context.</p>
<pre class="poc">{evidence}</pre>
<p>Evidence artifact: <code>{f.get('evidence_pointer') or 'per advisory'}</code>
&middot; Advisory: reports/{quote(f.get('id', ''))}_*.md</p>
</div>""")

    if informational:
        sections.append("<h2>Informational Observations (unverified)</h2><ul>")
        for f in informational[:20]:
            sections.append(f"<li>[{f.get('severity', 'info').upper()}] "
                            f"{f.get('title', '')} <i>(no PoC — not a vulnerability)</i></li>")
        sections.append("</ul>")

    if untested:
        sections.append(f"<h2>Coverage Honesty</h2><p>{len(untested)} item(s) were "
                        "not worked to completion and remain unverified surface:</p><ul>")
        for l in untested[:15]:
            sections.append(f"<li><code>{str(l.get('value', ''))[:80]}</code> "
                            f"({l.get('type')}/{l.get('status')})</li>")
        sections.append("</ul>")

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Security Assessment — {target}</title>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
<script>if (window.mermaid) mermaid.initialize({{startOnLoad: true}});</script>
<style>
body {{ font-family: -apple-system, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #1a1a2e; }}
.meta {{ color: #666; font-size: 0.85rem; }}
.summary {{ background: #f4f6fb; padding: 1rem; border-radius: 8px; }}
.finding {{ border: 1px solid #ddd; border-left: 5px solid #999; padding: 1rem; margin: 1rem 0; border-radius: 6px; }}
.sev-critical {{ border-left-color: #b3001b; }} .sev-high {{ border-left-color: #e8590c; }}
.sev-medium {{ border-left-color: #f0a500; }} .sev-low {{ border-left-color: #74a800; }}
.crit {{ color: #b3001b; font-weight: 600; }} .high {{ color: #e8590c; font-weight: 600; }}
.med {{ color: #b07c00; font-weight: 600; }} .low {{ color: #558000; font-weight: 600; }}
pre.poc {{ background: #0d1117; color: #c9d1d9; padding: 0.75rem; border-radius: 6px; overflow-x: auto; font-size: 0.85rem; }}
code {{ background: #eef; padding: 0.1rem 0.3rem; border-radius: 3px; }}
</style></head><body>
{"".join(sections)}
</body></html>"""

    out = REPORTS_DIR / "client_report.html"
    REPORTS_DIR.mkdir(exist_ok=True)
    out.write_text(html)
    print(f"[OK] Client report written: {out} ({len(confirmed)} confirmed, "
          f"CVSS templates + Mermaid chains included; refine vectors per finding)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Client-facing HTML report export")
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("export", help="Write reports/client_report.html")
    args = parser.parse_args()
    export()
